title: HTTP Error
baseurl: ""
email: ando@sqroot.eu
url: "https://error.sqroot.eu"
markdown: kramdown
exclude: [README.md, LICENSE.md]
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
